[project]
name = "audio-processing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.0.1",
    "librosa>=0.11.0",
    "matplotlib>=3.10.7",
    "scipy>=1.16.2",
]
